name: Build APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Add google services 
      - name: Create google-services.json
        # This writes the content of github secret into the expected file path
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json 

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

